.PHONY:all
all:selectechoserver   selectechoclient
selectechoserver:  
	gcc selectechoserver.c -o selectechoserver
selectechoclient:  
	gcc selectechoclient.c -o selectechoclient
clean:  
	rm -f selectechoserver selectechoclient
