.PHONY:all
all:thread1 thread2 thread3 thread3 thread4 thread5 thread6 thread7  
thread1:  
	gcc thread1.c -lpthread -o thread1 -D_REENTRANT
thread2:  
	gcc thread2.c -lpthread -o thread2 -D_REENTRANT
thread3:  
	gcc thread3.c -lpthread -o thread3 -D_REENTRANT
thread4:  
	gcc thread4.c -lpthread -o thread4 -D_REENTRANT
thread5:  
	gcc thread5.c -lpthread -o thread5 -D_REENTRANT
thread6:  
	gcc thread6.c -lpthread -o thread6 -D_REENTRANT
thread7:  
	gcc thread7.c -lpthread -o thread7 -D_REENTRANT
clean:  
	rm -f thread1 thread2 thread3 thread4 thread5 thread6 thread7
